language: python
before_install:
- echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- mkdir -p ~/.ssh
- chmod 700 ~/.ssh
- openssl aes-256-cbc -K $encrypted_6b10a682c05b_key -iv $encrypted_6b10a682c05b_iv
  -in ot-ot-gh-pages.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval "$(ssh-agent -s)"
- ssh-add ~/.ssh/id_rsa
- git config --global user.email "<travis-ci@owntracks.org>"
- git config --global user.name "OwnTracks (via TravisCI)"
- git config --global push.default simple
python:
- '2.7'
install: pip install -r requirements.txt
script:
- git clone git@github.com:owntracks/owntracks.git
- cd owntracks
- git checkout gh-pages
- ls -l booklet
- cd ..
- git clone https://github.com/owntracks/booklet.git
- cd booklet
- mkdocs build --clean
- ls -l _site
- cp -R _site/* ../owntracks/booklet/
- cd ../owntracks/booklet/
- git status
- git add .
- if [ -n "$(git status --porcelain)" ]; then  git commit -m 'TravisCI rebuild' -a;
  fi
- git push
notifications:
  slack:
    secure: Dh/vTZOnZt2XagniygSWq1hmKoj8pDQu6gVS5o9drHmlbITP+tPw/cww7t+2S92/z7A2ImCYobp4Nd2a54iCGdntt3zgNepqqMhY17rM5IKUHoG8XbYTHdSI2CxV6oCdX9i050IBu9H6ivwDk2LU6wjgMg3c08bYtqIwElELNKFD7JQtJiD8snsOuL/3Ze8nOYhhTgSeBnw7J7NW/FHeAuuQnvurJ70hSjzRv1JNA9m14GFyic/QtnVIHBYe3s1uTiv1Nv6BIrH80BhIo0CkHooG3IgziBTtfwfWbpDjJp0bOQ3+GzyeFjugmg4K04PqRNxJ40QuiTpY837RwtjjzJEKbqnW0ReUwMrdD/du+aCDcCijpSO16Vu5KbE88FOYkldaCQhfaCelOwgqLgRkvCFKIihT/tfUV3x2ZlhtYWInqMgo/TIUUrOFC3tvfS+2qqH/S/9g1PeBumPPue6ixdY2DcxDP0hXhDHjy2jST8Gjs7Jmn3E8HsQ2ON39BTg3H0kIAlJciPnv2ADSMyiVwXyb28FYnkD7pvBvU7jHkCNF2CDY1799zsswtnxmA+cd3QL6CEB0b+pn4vCnl/vSmWp2b0UnUn+i8b2S/LbdFbfcwI1ZA7749fcACPQxLS50AVtNXfyxWXHBzwPZXt4R1OpgZb03DfCF06W/VgD2/mg=
