site_name: OwnTracks Booklet
site_url: http://owntracks.org
site_author: OwnTracks.org
site_favicon: favicon.ico
repo_url: https://github.com/owntracks
site_dir: _site
pages:
- Intro: 'index.md'
- Guide:
    - 'What it does': 'guide/whathow.md'
    - 'User interface': 'guide/ui.md'
    - 'Scenarios': 'guide/scenarios.md'
    - 'MQTT': 'guide/mqtt.md'
    - 'Topics': 'guide/topics.md'
    - 'Broker': 'guide/broker.md'
    - 'Apps': 'guide/apps.md'
    - 'Clients': 'guide/clients.md'
    - 'Friends': 'guide/friends.md'
    - 'Waypoints': 'guide/waypoints.md'
    - 'Beacons': 'guide/beacons.md'
    - 'Bridging': 'guide/bridge.md'
- Features:
    - 'Hosted': 'features/hosted.md'
    - 'Security': 'features/security.md'
    - 'TLS': 'features/tls.md'
    - 'Location': 'features/location.md'
    - 'TID': 'features/tid.md'
    - 'Friends': 'features/friends.md'
    - 'Card': 'features/card.md'
    - 'Waypoints': 'features/waypoints.md'
    - 'Beacons': 'features/beacons.md'
    - 'Pedometer': 'features/pedometer.md'
    - 'Settings': 'features/settings.md'
    - 'LBS': 'features/lbs.md'
    - 'Comparison': 'features/comparison.md'
    - 'Android': 'features/android.md'
    - 'iOS': 'features/ios.md'
    - 'Remoteconfig': 'features/remoteconfig.md'
    - 'Debugging': 'features/debug.md'
- API:
    - 'JSON': 'tech/json.md'
    - 'QR': 'tech/qr.md'
    - 'Code': 'tech/program.md'
- Sundry:
    - 'Terminology': 'terminology.md'
    - 'Privacy': 'privacy.md'
    - 'People': 'people.md'
    - 'Ideas': 'ideas.md'
    - 'Answers': 'faq.md'
    - 'Press': 'press.md'

theme: readthedocs
markdown_extensions: [abbr,attr_list,def_list,footnotes,tables,admonition,toc]
